name: 'setup-mold'
description: 'Makes mold linker available on Unix-based OS'
author: 'Warchant'
inputs:
  version:
    description: 'mold version'
    required: false
    # https://github.com/rui314/mold/releases/tag/v1.0.3
    default: 'v1.0.3'
  default:
    description: 'If true, will replace /usr/bin/ld with mold'
    required: false
    default: false
branding:
  icon: 'arrow-up'
  color: 'green'
runs:
  using: 'node16'
  main: 'dist/index.js'