name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        default: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup mold
      uses: ./
      with: 
        version: 1.1.0
        make_default: ${{ matrix.default }}
    - name: run mold
      run: |
        which mold
        mold --help
    - name: run ld, expect to be mold
      if: matrix.default == true
      run: |
        which ld
        ld --help | grep "Report error if DT_TEXTREL is set"
    - name: run ld, expect to not be mold
      if: matrix.default == false
      run: |
        which ld
        ld --help | grep -v "Report error if DT_TEXTREL is set"
    - run: echo $PATH