name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        default: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup mold
      uses: ./
      with: 
        default: ${{ matrix.default }}
    - name: run mold
      run: |
        which mold
        mold --help
    - name: run ld
      run: |
        which ld
        ld --help